#!/bin/bash

clear=False

rand() {
	# Get a list of all the albums
	albums="$(mpc list album)"
	# Split bu newline
	readarray -t splitted <<<"$albums"
	# Get the size
	size=${#splitted[@]}
	# Get a random index
	index=$(($RANDOM % $size))
	# Get a random album
	album=${splitted[$index]}
	if [[ $clear = True ]]; then
		mpc clear
	fi
	# Find all the tracks that belong to this album
	mpc findadd album "$album"
	echo "Added the album: $album"
	# Play just to be sure
	mpc play
}


next() {
	# Get a list containing the album of each track in the queue. Meaning we have as many entries per album as there are tracks in the queue
	playlist="$(mpc -f %album% playlist)"
	# Split by newline
	readarray -t splitted <<<"$playlist"
	# Get the index of the currently playing track
	i="$(mpc -f %position% current)"
	# Get the album of the currently playing track
	current="$(mpc -f %album% current)"
	# Calculate how many tracks there are
	max=$(( ${#splitted[@]} ))
	finished=False
	# Now we loop up, for loops are wonky so while
	while [[ $i -lt $max && $finished = False ]]
	do
		# Get the album at this index
		album="${splitted[i]}"
		# As long as the album for this track is the same as the one for the current track, keep counting
		if [[ "$current" = "$album" ]]; then
			let "i++"
		else
			finished=True
		fi
	done
	let "i++"
	# Play the track at 1 higher than the last track in the album
	mpc play "$i"
	if [[ $clear = True ]]; then
		# To clear, we simply keep removing tracks from the queue until we reach 0
		j=$i
		let "j--"
		while [[ $j -gt 0 ]]
		do
			mpc del "$j"
			let "j--"
		done
	fi
}

prev() {
	playlist="$(mpc -f %album% playlist)"
	readarray -t splitted <<<"$playlist"
	i="$(mpc -f %position% current)"
	let "i--"
	prev="${splitted[i]}"
	finished=False
	while [[ $finished = False ]]
	do
		album="${splitted[i]}"
		if [[ "$prev" = "$album" ]]; then
			let "i--"
		else
			finished=True
		fi
	done
	if [[ $i -lt 1 ]]; then
		i=1
	fi
	mpc play "$i"

}

crop() {
	playlist="$(mpc -f %album% playlist)"
	readarray -t splitted <<<"$playlist"
	i="$(mpc -f %position% current)"
	let "i--"
	curr=${splitted[i]}
	j=$i
	counter=$j
	max=$(( ${#splitted[@]} ))
	while [[ $j -le $max ]]
	do
		album="${splitted[$j]}"
		if [[ "$album" != "$curr" ]]; then
			mpc del "$counter"
		else
			let "counter++"
		fi
		let "j++"
	done
	j=$i
	while [[ $j -gt 0 ]]
	do
		album="${splitted[$j]}"
		if [[ "$album" != "$curr" ]]; then
			mpc del "$j"
		fi
		let "j--"
	done
}

status() {
	mpc status
}

playlist() {
	playlist="$(mpc -f '%albumartist% - %album%' playlist)"
	readarray -t splitted <<<"$playlist"
	declare -A seen
	uniq=()
	for album in "${splitted[@]}"; do
		[[ ${seen[$album]} ]] && continue
		uniq+=( "$album" )
		seen[$album]=x
	done
	printf '%s\n' "${uniq[@]}"
}

current() {
	echo "$(mpc -f '%albumartist% - %album%' current)"
}

play() {
	index="$1"
	if [[ $index -lt 1 ]]; then
		index=1
	fi
	playlist="$(mpc -f %album% playlist)"
	readarray -t splitted <<<"$playlist"
	i=0
	newIndex=0
	prev=""
	while [[ $i -lt $index ]]
	do
		album="${splitted[i]}"
		if [[ "$album" != "$prev" ]]; then
			let "i++"
		fi
		let "newIndex++"
	done
	mpc play "$newIndex"
	if [[ $clear = True ]]; then
		j=$newIndex
		let "j--"
		while [[ $j -gt 0 ]]
		do
			mpc del "$j"
			let "j--"
		done
	fi
}

queue() {
	playlist="$(mpc -f '%albumartist% - %album%' playlist)"
	readarray -t splitted <<<"$playlist"
	current="$(mpc -f '%albumartist% - %album%' current)"
	next=""
	for album in "${splitted[@]}"; do
		if [[ "$album" != "$current" ]]; then
			next="$album"
			break
		fi
	done
	echo "$next"
}

help() {
	# Should probably write a better help but w/e
	echo "Unknown command: $1"
	echo "Usage: mpa <command> [options]"
	echo "Read the README for more info"
}

i=0

opt="$1"

if [[ $* = *-c ]]; then
	clear=True
fi

case "$opt" in
	random) rand ;;
	next) next ;;
	status) status ;;
	playlist) playlist ;;
	current) current ;;
	queued) queue ;;
	play) play $2 ;;
	crop) crop ;;
	*) help "$1" ;;
esac
