#!/bin/bash

albums="$(mpc list album)"
readarray -t splitted <<<"$albums"
size=${#splitted[@]}
index=$(($RANDOM % $size))
album=${splitted[$index]}
mpc clear
mpc findadd album "$album"
mpc play
echo "Now playing: $album"
